CREATE TABLE EMPLOYEES(
ID INT NOT NULL,
NAME VARCHAR (20) NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR (25),
SALARY INTEGER,
DEPARTMENT TEXT,
PRIMARY KEY (ID)
);
INSERT INTO EMPLOYEES VALUES
(1, 'Ramesh', 32, 'Ahmedabad', 2000, 'Sales'),
(2, 'Khilan', 25, 'Delhi', 1500, 'Finance'),
(3, 'Kaushik', 23, 'Kota', 2000, 'IT'),
(4, 'Chaitali', 25, 'Mumbai', 6500, 'Customer Service'),
(5, 'Hardik', 27, 'Bhopal', 8500, 'Sales'),
(6, 'Komal', 22, 'Hyderabad', 4500, 'IT'),
(7, 'Muffy', 24, 'Indore', 10000, 'Finance');

SELECT * FROM EMPLOYEES;

SELECT SUM(SALARY) AS SUM_OF_SALARIES
FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVG_OF_SALARIES
FROM EMPLOYEES;

SELECT COUNT(DEPARTMENT) AS COUNT_OF_DEPARTMENTS
FROM EMPLOYEES;

SELECT MIN(SALARY) AS MIN_OF_SALARIES
FROM EMPLOYEES;

SELECT MAX(SALARY) AS MAX_OF_SALARIES
FROM EMPLOYEES;